- import_role: name=icos.python3

- name: Create jyctl user
  user:
    name: jyctl
    home: /opt/jyctl
    groups: docker
    append: yes
  register: _user

- name: Change access rights on /opt/jyctl
  file:
    path: /opt/jyctl
    mode: "0700"

- name: Login to registry
  become: yes
  become_user: jyctl
  community.general.docker_login:
    registry_url: "{{ jbuild_registry.url }}"
    username: "{{ jbuild_registry.username }}"
    password: "{{ jbuild_registry.password }}"

- name: Create virtual env
  pip:
    virtualenv_python: python3.8
    virtualenv: /opt/jyctl/venv
    name:
      - click
      - docker
    state: present

- name: Copy jyctl.py
  copy:
    src: jyctl.py
    dest: /opt/jyctl/jyctl.py
    mode: +x
    # This is useful when developing jyctl.py directly on a server.
    force: "{{ jbuild_force | default(True) | bool }}"

- name: Add keys to authorized_keys
  authorized_key:
    user: jyctl
    key_options: 'command="/opt/jyctl/jyctl.py"'
    key: |
      {% for elt in _jbuild_user_keys.results -%}
      {{ elt.public_key }}
      {% endfor %}

# The jupyter playbook by default disallows ssh login to most users.
- name: Allow jyctl to login
  copy:
    dest: /etc/ssh/sshd_config.d/jyctl_allow_users.conf
    content: |
      AllowUsers jyctl
  notify: reload sshd
