- hosts: flexextract_host
  become: true
  vars_files:
    - vault.yml
  pre_tasks:
    - name: Create flexextract storage pool
      tags: pool
      shell: >-
        /snap/bin/lxc storage show flexextract > /dev/null 2>&1 ||
        /snap/bin/lxc storage create flexextract btrfs size=50GB
      register: _r
      changed_when:
        - '"Storage pool flexextract created" in _r.stdout'

    - name: Create the flexextract container
      tags: lxd
      lxd_container:
        name: flexextract
        state: started
        profiles:
          - default
          - ssh_root
        source:
          type: image
          mode: pull
          server: https://cloud-images.ubuntu.com/releases
          protocol: simplestreams
          alias: "18.04"
        config:
          security.nesting: "true"
          limits.cpu: "10"
          limits.memory: "55GB"
        devices:
          root:
            path: /
            type: disk
            pool: flexextract
            size: "50GB"
          ida:
            path: "/home/ida"
            source: "/disk/data/ida"
            type: disk
          flexextract:
            path: /data/flexextract
            source: /disk/data/flexextract
            type: disk
            readonly: "False"
        wait_for_ipv4_addresses: true
        timeout: 600
      register: _lxd

  roles:
    - role: icos.lxd_forward
      lxd_forward_ip: "{{ _lxd.addresses.eth0 | first }}"
      lxd_forward_name: flexextract

    - role: icos.certbot2
      tags: cert
      certbot_name: flexextract
      certbot_domains:
        - flexextract.icos-cp.eu

    - role: icos.nginxsite
      tags: nginx
      nginxsite_name: flexextract
      nginxsite_file: files/flexextract.conf


- hosts: flexextract
  become: true
  vars_files:
    - vault.yml
  vars:
    flexextract_sudo: true
  roles:
    - role: icos.lxd_guest
      tags: guest

    - role: icos.docker
      tags: docker

    - role: icos.flexextract
      tags: flexextract
      flexextract_src_dir: /tmp/docker_flexextract_7.1.0

    - role: icos.sshlogin
      tags: sshlogin
      sshlogin_dst: flexpart
      sshlogin_src_user: root
      sshlogin_dst_user: ubuntu

    - role: icos.superuser
      tags: superuser
      superuser_disable_coredump: true
      superuser_list: "{{ vault_flexextract_superuser_list }}"

  tasks:
    - name: Install additional ssh keys
      tags: keys
      authorized_key:
        user: flexextract
        state: present
        key: "{{ vault_flexextract_extra_keys }}"
