# Try to set up /data so that it looks the same on all our servers.
# The LXD "icosdata" profile will make the following paths available.
#
# Update LXD profile
#   deploy icosdata -lfsicos2* profile
#
# Update the bind-mounts on fsicos2
#   deploy icosdata -lfsicos2* bind



# FSICOS 1

- hosts: fsicos.lunarc.lu.se
  handlers:
    - name: Reload NFS server
      service:
        name: nfs-server
        state: reloaded
  tasks:
    - name: Create /etc/exports.d directory
      tags: exports
      file:
        path: "/etc/exports.d"
        state: directory

    - name: Add icosdata exports
      tags: exports
      copy:
        dest: /etc/exports.d/icosdata.exports
        content: |
          /disk/data/flexpart		      fsicos*.lunarc.lu.se(ro)
      notify: Reload NFS server



# FSICOS2

- hosts: fsicos2.lunarc.lu.se
  handlers:
    - name: Reload NFS server
      service:
        name: nfs-server
        state: reloaded
  tasks:
    - name: Do bind-mount local data
      mount:
        path: "{{ item.path }}"
        src:  "{{ item.src }}"
        fstype: none
        opts: "bind{{ item.opts | default('') }}"
        state: mounted
      loop:
        - path: /data/stiltweb
          src: /disk/data/stiltweb
          opts: ",ro"

        - path: /data/project
          src: /disk/data/project

        - path: /data/dataAppStorage
          src: /disk/data/dataAppStorage
          opts: ",ro"

        - path: /data/stilt_legacy
          src: /disk/data/stilt
          opts: ",ro"

    - name: Create nfs mount points
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - /data/stilt
        - /data/flexpart
        - /share/fsicos3

    - name: Mount nfs data
      tags: mount
      mount:
        path: "{{ item.path }}"
        src: "{{ item.src }}"
        fstype: nfs
        opts: "{{ item.opts | default('ro') }}"
        state: mounted
      loop:
        - path: /share/fsicos3
          src: fsicos3.lunarc.lu.se:/incoming
          opts: rw

        - path: /data/project/eurocom
          src: fsicos3.lunarc.lu.se:/data/project/eurocom

        - path: /data/stilt
          src: fsicos3.lunarc.lu.se:/pool/ute/stilt/RINGO/T1.3/STILT

        # - path: /data/flexpart
        #   src: fsicos.lunarc.lu.se:/disk/data/flexpart

        # - path: /data/project/interpolation
        #   src: fsicos3.lunarc.lu.se:/data/project/interpolation

        - path: /data/project/stc
          src: fsicos3.lunarc.lu.se:/data/project/stc

    - name: Export data via nfs
      tags: export
      blockinfile:
        marker: "# {mark} icosdata"
        create: yes
        path: /etc/exports
        block: |
          /data/flexextract         fsicos*.lunarc.lu.se(ro)
          /disk/data/project        fsicos*.lunarc.lu.se(ro)
          /disk/data/flexpart/meteo fsicos*.lunarc.lu.se(ro)
          /disk/data/dataAppStorage fsicos*.lunarc.lu.se(ro)
          /disk/data/stiltweb       fsicos*.lunarc.lu.se(ro)
          /disk/data/obspack        fsicos*.lunarc.lu.se(ro)
          /disk/data/stilt          fsicos*.lunarc.lu.se(ro)
      notify: Reload NFS server


# FSICOS3

- hosts: fsicos3.lunarc.lu.se
  handlers:
    - name: Reload NFS server
      service:
        name: nfs-server
        state: reloaded
  tasks:
    - name: Install nfs-kernel-server
      apt:
        name: nfs-kernel-server
        state: present

    - name: Create /incoming
      tags: incoming
      zfs:
        name: pool/incoming
        state: present
        extra_zfs_properties:
          mountpoint: /incoming

    - name: Mount nfs data
      tags: nfs
      mount:
        src: "{{ item.src }}"
        path: "{{ item.path }}"
        state: mounted
        fstype: nfs
        opts: "{{ item.opts | default('ro') }}"
      loop:
        - path: /data/flexextract
          src: fsicos2.lunarc.lu.se:/data/flexextract

        - path: /data/flexpart/meteo
          src: fsicos2.lunarc.lu.se:/disk/data/flexpart/meteo

        - path: /data/dataAppStorage
          src: fsicos2.lunarc.lu.se:/disk/data/dataAppStorage

        - path: /data/stiltweb
          src: fsicos2.lunarc.lu.se:/disk/data/stiltweb

        - path: /data/obspack
          src: fsicos2.lunarc.lu.se:/disk/data/obspack

        - path: /data/stilt_legacy
          src: fsicos2.lunarc.lu.se:/disk/data/stilt

        - path: /data/project/climbeco
          src: fsicos2.lunarc.lu.se:/disk/data/project/climbeco

    - name: Export data via nfs
      tags: export
      blockinfile:
        marker: "# {mark} icosdata"
        create: yes
        path: /etc/exports
        block: |
          # The 'no_subtree_check' is to avoid warnings about the default behaviour having changed.
          /incoming                        fsicos*.lunarc.lu.se(rw,no_root_squash,no_subtree_check)
          /data/project/stc                fsicos*.lunarc.lu.se(ro,no_subtree_check)
          /data/project/interpolation      fsicos*.lunarc.lu.se(ro,no_subtree_check)
          /data/project/eurocom            fsicos*.lunarc.lu.se(ro,no_subtree_check)
          /pool/ute/stilt/RINGO/T1.3/STILT fsicos*.lunarc.lu.se(ro,no_subtree_check)
      notify: Reload NFS server

    - name: Do bind-mount local data
      mount:
        path: "{{ item.path }}"
        src:  "{{ item.src }}"
        fstype: none
        opts: "bind{{ item.opts | default('') }}"
        state: mounted
      loop:
        - path: /data/stilt
          src: /pool/ute/stilt/RINGO/T1.3/STILT
          opts: ",ro"
