# https://hub.docker.com/r/onlyoffice/documentserver-ee/
onlyoffice_version: 6.3.0
onlyoffice_port: 8201

onlyoffice_home: /docker/onlyoffice
onlyoffice_build_dir: "{{ onlyoffice_home }}/build"

onlyoffice_domain: onlyoffice.icos-cp.eu
onlyoffice_cert_name: onlyoffice
onlyoffice_site_name: onlyoffice
