- name: Add kanboard user
  user:
    name: kanboard
    append: yes

- name: Copy kanboards nginx conf to nginx/conf.d
  copy:
    src: kanban.conf
    dest: /etc/nginx/conf.d/kanban.conf
    owner: root
    group: root
    mode: 0700
  notify: reload nginx config

- name: Create path for docker compose file
  file: path=/disk/data/kanboard/kanboard/ state=directory

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /disk/data/kanboard/kanboard/docker-compose.yml
    owner: kanboard
    mode: g=rw

- name: Run kanboard docker compose
  docker_service:
    project_src: /disk/data/kanboard/kanboard
    state: present

#To restore from backup you must set the variable restore in devops/vars.yml to true 
- name: Copy backed up data for kanboard
  copy: 
    src: "{{ backup_path }}kanboard/rsyncBackup/db.sqlite"
    dest: /disk/data/kanboard/data
    owner: root
    mode: g=rw
  when: restore

- name: Change owner of kanboard database
  shell: "docker exec kanboard_kanboard_1 chown -R nginx:nginx /var/www/app/data"
  when: restore
