- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ stiltweb_username }}"
    group: "{{ stiltweb_username }}"
  with_items:
    - "{{ stiltweb_statedir }}"
    - "{{ stiltweb_bin_dir }}"

- import_role:
    name: icos.certbot
  vars:
    - certbot_domains: [stilt.icos-cp.eu]
    - nginx_conf_name: stilt

- name: Run the jarservice role
  import_role:
    name: icos.jarservice
  vars:
    username        : "{{ stiltweb_username }}"
    extra_groups    : docker
    jarfile         : "{{ stiltweb_jar_file }}"
    servicename     : "{{ stiltweb_servicename }}"
    servicetemplate : "{{ stiltweb_template }}"
    nginxconfig     : "{{ stiltweb_nginxconfig }}"
  when:
    - stiltweb_jar_file is defined

- name: Add systemd service files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src:  stiltweb_tunnel@.service.j2,
        dest: /etc/systemd/system/stiltweb_tunnel@.service }
    - { src: stiltweb_tunnels.target.j2,
        dest: /etc/systemd/system/stiltweb_tunnels.target }
  notify:
    - reload systemd config

- block:
  - import_tasks: stiltweb_build_hosts.yml

  - import_tasks: stiltweb_ssh_config.yml
    become: yes
    become_user: "{{ stiltweb_username }}"

  - import_tasks: stiltweb_restart_tunnels.yml
  when:
    - stiltweb_no_tunnels is not defined
    - groups.stiltcluster
