- name: Create .ssh dir
  file:
    path: "{{ _user.home }}/.ssh"
    mode: 0700
    state: directory

- name: Install ssh keys
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0600
  with_items:
    - {src: stiltweb.rsa, dest: "{{ _user.home }}/.ssh/id_rsa"}
    - {src: stiltweb.pub, dest: "{{ _user.home }}/.ssh/id_rsa.pub"}

- name: Create .ssh/config
  template:
    src: ssh-config.j2
    dest: "{{ _user.home }}/.ssh/config"
    mode: 0600

- name: Add all stiltcluster hosts to our known_hosts file
  known_hosts:
    name: "{{ item.ip }}"
    key: >-
      {{ item.host }},{{ item.ip }}
      ecdsa-sha2-nistp256
      {{ item.host_key }}
    state: present
  with_items: "{{ stiltweb_remote_hosts }}"
