modules:
  http_sign_in:
    prober: http
    timeout: 10s
    http:
      valid_status_codes: []
      method: GET

  https_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      fail_if_ssl: false
      fail_if_not_ssl: true
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      valid_status_codes: [200]
      no_follow_redirects: false
      preferred_ip_protocol: "ip4"
