- name: Copy build directory
  copy:
    dest: "{{ onlyoffice_home }}/"
    src: build

- name: Install runtime environment file
  copy:
    mode: "o-r"
    dest: "{{ onlyoffice_home }}/onlyoffice.env"
    content: |
      # JWT == JSON Web Tokens. This is how Nextcloud authenticates
      # itself to OnlyOffice.
      JWT_ENABLED=true
      JWT_SECRET={{ onlyoffice_secret | mandatory }}

      # Setting this to false will make the documentserver's entrypoint
      # script allow unauthorized HTTPS connections. Use only for testing.
      JWT_REJECT_UNAUTHORIZED=true

# https://helpcenter.onlyoffice.com/server/integration-edition/docker/docker-installation.aspx#Registering
- name: Copy license.lic
  copy:
    src: license.lic
    dest: "{{ onlyoffice_home }}/volumes/data/"

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: "{{ onlyoffice_home }}"

- name: Install parsetime environment file
  copy:
    dest: "{{ onlyoffice_home }}/.env"
    content: |
      ONLYOFFICE_PORT={{ onlyoffice_port }}
      ONLYOFFICE_VERSION={{ onlyoffice_version }}

- name: Build and start
  docker_compose:
    project_src: "{{ onlyoffice_home }}"
    build: yes
    state: present
    restarted: yes
