- include_role: name=icos.certbot

- name: Run the jarservice role
  include_role:
    name: icos.jarservice
  vars:
    username        : "{{ cpmeta_username }}"
    jarfile         : "{{ cpmeta_jar_file }}"
    apptemplate     : "{{ cpmeta_apptemplate }}"
    nginxconfig     : "{{ cpmeta_nginxconfig }}"
    servicename     : "{{ cpmeta_servicename }}"
    servicetemplate : "{{ cpmeta_template }}"

- name: Copy SSL certs and private key for Handle.net client
  copy:
    src: ssl
    dest: /home/{{ cpmeta_username }}/
    owner: "{{ cpmeta_username }}"
    group: "{{ cpmeta_username }}"

- name: Create metaAppStorage directory (if not present), take ownership
  file:
    path: "{{ cpmeta_filestorage_target }}"
    state: directory
    owner: "{{ cpmeta_username }}"
    group: "{{ cpmeta_username }}"

- block:
    - name: Ensure that the remotebackup script is present
      file:
        path: "{{ cpmeta_remotebackup_bin }}"
        mode: +x

    - name: Install cronjob to backup cpmetas fileStorage
      cron:
        name: Backup cpmeta fileStorage
        job: >-
          {{ cpmeta_remotebackup_bin }} -La {{ cpmeta_filestorage_target }} meta
        special_time: hourly
  when: cpmeta_enable_remotebackup
