stilt_master_host: stilt.icos-cp.eu
stiltcluster_username: stiltcluster
stiltcluster_servicename: stiltcluster
# Sadly, we cannot use our {{role_path}} to define this path, since that
# variable wont be resolved until in the role_included jarservice, by which
# point it'll point to jarservice.
# https://github.com/ansible/ansible/issues/15439
stiltcluster_template: roles/icos.stiltcluster/templates/stiltcluster.service.j2
stiltcluster_appconfig:  roles/icos.stiltcluster/files/local.conf

