---
- name: Include vars
  include_vars: vars.yml

- name: Include vault
  include_vars: vault.yml

- include_role: name=icos.certbot
  vars:
    - certbot_domains: [apply.fieldsites.se]
    - nginx_conf_name: sites-aquanet-form

- name: Copy nginx conf
  template:
    src: sites-aquanet-form.conf
    dest: /etc/nginx/conf.d/
    mode: 0700
  notify: reload nginx config

- name: Create project directory
  file:
    path: "{{ project_dir }}"
    state: directory
    recurse: yes

- import_tasks: bitbucket.yml

- name: Pull source from git
  git:
    repo: "{{ vault_aquanet_form_git_repo }}"
    dest: "{{ project_dir }}/repo"
    key_file: "{{ project_dir }}/.ssh/id_rsa"

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ project_dir }}/docker-compose.yml"

- name: Run docker-compose
  docker_service:
    project_src: "{{ project_dir }}"
    state: present
  notify: reload nginx config
