stilt_nfs_icosprod1_ip: 192.168.99.10
stilt_nfs_exports: |
  /tmp		{{ stilt_nfs_icosprod1_ip }}(ro)

stiltcluster_port: 2561
stiltcluster_maxcores: 0

flexpart_install_run: true
flexpart_export_output_to: "192.168.99.10(ro,no_subtree_check)"

meta_tunnel_to_ip: 192.168.99.10
meta_tunnel_to_host: centos


nginx_set_real_ip_from: |
    set_real_ip_from 192.168.99.10; # centos
