stiltcluster_ip: 192.168.99.10
stiltcluster_port: 2562

stilt_nfs_icosprod2_host: 192.168.99.30
stilt_nfs_mounts:
  - path: "/mnt/bionic-tmp"
    src: "{{ stilt_nfs_icosprod2_host }}:/tmp"

flexpart_ssh_users: ['vagrant']
flexpart_ssh_remote_host: "bionic"
flexpart_ssh_remote_ip: "192.168.99.30"

pgrep_rdflog_instance:
  suffix: rdflog
  peer_host: 192.168.99.40
  peer_port: "{{ rdflog_db_port }}"
  peer_user: "{{ rdflog_rep_user }}"
  peer_pass: "{{ rdflog_rep_pass }}"
  peer_cert: roles/icos.rdflog/files/server.crt
  peer_slot: centos


meta_tunnel_from_ip: 192.168.99.30
certbot_fake_certificate: True
