- name: Create cpdata user
  user:
    name: "{{ cpdata_user }}"
    home: "{{ cpdata_home }}"
    shell: /bin/bash

- name: Create dataAppStorage directory (if not present), take ownership
  file:
    path: "{{ cpdata_filestorage_target }}"
    state: directory
    owner: "{{ cpdata_user }}"
    group: "{{ cpdata_user }}"
