- name: Download borg binary
  get_url:
    url: "{{ borg_url }}"
    dest: "{{ borg_bin }}_{{ borg_ver }}"
    checksum: "{{ borg_checksum | default(omit) }}"
    mode: +x
  register: _download

# This is used when testing out new versions for the first time.
- name: Display checksum of downloaded binary
  debug:
    msg: "Binary have checksum sha1:{{ _download.checksum_dest }}"
  when: not borg_checksum

- name: Test downloaded binary
  command: |
    {{ _download.dest }} --version
  register: _r
  failed_when: not _r.stdout.startswith('borg')
  changed_when: no

# Migration from bbclient, which downloaded without symlinking.
- name: Maybe remove non-symlink
  shell: "[ -h {{ borg_bin }} ] || { echo removing; rm {{ borg_bin }}; }"
  register: _r
  changed_when: "'removing' in _r.stdout"

- name: Create {{ borg_bin }} symlink
  file:
    dest: "{{ borg_bin }}"
    src: "{{ _download.dest }}"
    state: link
