# This package is required by the iptables_raw module.
- name: Install the iptables-persistent package
  apt:
    name: iptables-persistent


- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"


# These are mostly copied from the default ufw rules.
- name: Setup default iptables rules
  iptables_raw:
    name: iptables_default
    weight: 10
    rules: |
      # allow all on loopback
      -A INPUT -i lo -j ACCEPT
      -A OUTPUT -o lo -j ACCEPT

      # allow all established connections
      -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      -A OUTPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT

      # drop invalid connections
      -A INPUT -m conntrack --ctstate INVALID -j DROP

      # icmp codes for INPUT
      -A INPUT -p icmp --icmp-type destination-unreachable -j ACCEPT
      -A INPUT -p icmp --icmp-type time-exceeded -j ACCEPT
      -A INPUT -p icmp --icmp-type parameter-problem -j ACCEPT
      -A INPUT -p icmp --icmp-type echo-request -j ACCEPT

      # icmp code for FORWARD
      -A FORWARD -p icmp --icmp-type destination-unreachable -j ACCEPT
      -A FORWARD -p icmp --icmp-type time-exceeded -j ACCEPT
      -A FORWARD -p icmp --icmp-type parameter-problem -j ACCEPT
      -A FORWARD -p icmp --icmp-type echo-request -j ACCEPT

      {% if iptables_enable_mdns -%}
      # Multicast mDNS for service discovery
      -A INPUT -p udp -d 224.0.0.251 --dport 5353 -j ACCEPT
      # Multicast UPnP for service discovery
      -A INPUT -p udp -d 239.255.255.250 --dport 1900 -j ACCEPT
      {% endif -%}


- name: Allow ssh through firewall
  iptables_raw:
    name: allow_ssh
    rules: >-
      -A INPUT -p tcp --dport 22 -j ACCEPT -m comment --comment 'ssh'
