nginx_conf_name: icosch
drupal_docker_port: 8120
mysql_docker_port: 3342
domain: www.icos-switzerland.ch
trusted_host: ^www\.icos-switzerland\.ch$
ssl_domains: [switzerland.icos-cp.eu,www.icos-switzerland.ch]
