nginx_conf_name: icosnl
drupal_docker_port: 8121
mysql_docker_port: 3343
domain: www.icos-netherlands.nl
trusted_host: ^www\.icos-netherlands\.nl$
ssl_domains: [icos-netherlands.nl,www.icos-netherlands.nl]
redirect_to_www: true
