name: ns
drupal_docker_port: 8104
mysql_docker_port: 3331
domain: nordspec.nateko.lu.se
trusted_host: ^nordspec\.nateko\.lu\.se$
database_prefix: drupal_
database_name: nordspecdb
database_user: nordspecdb
