- import_tasks: auth.yml
  tags: registry_auth

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: "{{ registry_home }}/"

# Not sure yet what this is for, generate it mostly to silence warning about
# "No HTTP secret provided" when starting the registry service.
- name: Create http secret
  shell: openssl rand -hex 20 | awk '{ print "REGISTRY_HTTP_SECRET=" $1 }' > .env
  args:
    chdir: "{{ registry_home }}"
    creates: .env

- name: Build and start
  community.docker.docker_compose:
    project_src: "{{ registry_home }}"
    build: yes
